version: "2"

services:
    arch:
        image: archlinux/base
        command: "echo Hello World!"
    ubuntu:
        image: ubuntu:16.04
        command: "echo Hello World!"
    alpine:
        image: alpine:3.7
        command: "echo Hello World!"
